language:
    - c

compiler: gcc
env: CFLAGS='-Wall -Werror'

matrix:
    include:
        - compiler: gcc
          env: CFLAGS='-Wall -Werror'

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install check cmake

script:
    - cmake .
    - make VERBOSE=1
